version: '0.0.1'

# Each Micro Service
services:
  # Used for getting access-tokens for the client
  auth:
    build:
      context: ./auth-server
      dockerfile: start-auth.Dockerfile
    volumes:
      - ./auth-server:/usr/src/app
    ports:
      - "3000:3000"