version: '3.8'

# Each Micro Service
services:
  # Used for getting access-tokens for the client
  auth-server:
    build:
      context: ./auth-server
      dockerfile: .Dockerfile
    container_name: Auth-Server
    ports:
      - "3500:3000"
    depends_on:
      - mongo-db

  # Recieves JWT from front-end, checks jwt is legit with auth server
  # This returns friend list data, chats all using json
  back-end:
    build:
      context: ./back-end
      dockerfile: .Dockerfile
    container_name: Back-End
    ports:
      - "4000:3000"


  # Signalling using Web Sockets passing internet data from client to peer using the ICE_FRAMEWORK with the signalling server
  # Communicates with back-end to get chats, friend data. Could use a web socket or just using the api.
  front-end:
    build:
      context: ./front-end
      dockerfile: .Dockerfile
    container_name: Front-End
    ports:
      - "3000:3000"
  
  # Seperate db for just Login Details: This is just placeholder db login details
  mongo-db:
    image: mongo
    restart: always
    container_name: Databases
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strong_password
    ports:
        - "27017:27017"
    volumes:
      - ./db-init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
    container_name: Reverse-Proxy
    ports:
      - "80:80"
      - "443:443"
