version: '3.8'

# Each Micro Service
services:
  # Used for getting access-tokens for the client
  auth:
    build:
      context: ./auth-server
      dockerfile: .Dockerfile
    ports:
      - "4000:3000"

  front-end:
    build:
      context: ./front-end
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"
  
  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
    ports:
      - "80:80"
      - "443:443"
