version: '0.0.1'

# Each Micro Service
services:
  # Used for getting access-tokens for the client
  auth:
    build:
      context: ./auth-server
      dockerfile: start-auth.Dockerfile
    volumes:
      - /auth-server
    ports:
      - "3000:3000"

  front-end:
    build:
      context: ./front-end
      dockerfile: front-end.Dockerfile
    volumes:
      - /front-end
    ports:
      - "4000:3000"