version: '3.8'

# Each Micro Service
services:
  # Used for getting access-tokens for the client
  auth:
    build:
      context: ./auth-server
      dockerfile: .Dockerfile
    ports:
      - "3500:3000"

  # Recieves JWT from front-end, checks jwt is legit with auth server
  # This returns friend list data, chats all using json
  back-end:
    build:
      context: ./back-end
      dockerfile: .Dockerfile
    ports:
      - "4000:3000"


  # Signalling using Web Sockets passing internet data from client to peer using the ICE_FRAMEWORK with the signalling server
  # Communicates with back-end to get chats, friend data. Could use a web socket or just using the api.
  front-end:
    build:
      context: ./front-end
      dockerfile: .Dockerfile
    ports:
      - "3000:3000"
  
  # Seperate db for just Login Details: This is just placeholder db login details
  auth-db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: auth_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: strong_password
    ports:
        - "27017:27017"

  nginx:
    build:
      context: ./nginx
      dockerfile: .Dockerfile
    ports:
      - "80:80"
      - "443:443"
