name: Auth Server CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./auth-server
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Running Docker Compose
        run: docker-compose up -d --build

      - name: Running Unit Tests
        working-directory: ./auth-server
        run: npm test

      - name: Running Integration Tests
        working-directory: ./auth-server
        run: npm test
