name: Auth Server CI CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./auth-server
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Running Docker Compose
        run: docker compose up -d

      - name: Installing Node Modules
        run: npm install

      - name: Waiting for all Services to Boot
        run: sleep 30
        
      - name: Running Unit Tests
        working-directory: ./auth-server
        run: npm run test:unit

      - name: Running Integration Tests
        working-directory: ./auth-server
        run: npm run test:int
