name: Auth-Server CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./auth-server
      
    steps:
      - uses: actions/checkout@v3
      - name: Running Docker Compose
      
      - run: docker compose up -d --build
      - name: Running Tests
        working-directory: ./auth-server
        run: |
          npm test
