name: Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./auth-server
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Building Image
        run: docker compose build

      - name: Docker Hub Login
        working-directory: ./auth-server
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Deploying to Docker Hub
        working-directory: ./auth-server
        run: docker-compose push damonmartin/comp3000-zephyr-rtc-final-year-project
