name: Deployment
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
    
    env:
      working-directory: ./auth-server
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH into VPS
        run: |
          sshpass -p "${{ secrets.VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@zephyr-rtc.damon-martin.co.uk <<EOF
            cd my-projects/ZephyrRTC-Final-Year-Project
            docker-compose down
            cd ..
            rm -r -f ./ZephyrRTC-Final-Year-Project
            git clone git@github.com:Damon-Martin/ZephyrRTC-Final-Year-Project.git
            cd ZephyrRTC-Final-Year-Project
            docker-compose up -d --build
          EOF
