name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Hub Login
        working-directory: ./auth-server
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Building Image
        working-directory: ./auth-server
        run: docker-compose up
          
      - name: Deploying to Docker Hub
        working-directory: ./auth-server
        run: docker-compose push damonmartin/comp3000-zephyr-rtc-final-year-project:v0.0.1
