name: Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Hub Login
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} docker.io

      - name: Building Image
        run: docker-compose build
          
      - name: Deploying to Docker Hub
        run: docker-compose push damonmartin/comp3000-zephyr-rtc-final-year-project:v1.0.0
