name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Auth-Tests:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installing Node Modules
        working-directory: ./auth-server
        run: npm install
        
      - name: Running Auth Server Integration Tests
        working-directory: ./auth-server
        run: npm run test:unit
  
  Component-Tests:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Installing Node Modules
        working-directory: ./front-end
        run: npm install
        
      - name: Running Component Tests (Type of Unit Test)
        working-directory: ./front-end
        run: npm run test:cypress-component
